"""empty message

Revision ID: 56bf9fce2d10
Revises: aa3d793217e3
Create Date: 2023-06-04 19:28:08.855887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bf9fce2d10'
down_revision = 'aa3d793217e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
