"""empty message

Revision ID: 1d4cba5142f4
Revises: d1a600144975
Create Date: 2023-06-05 20:35:43.556421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4cba5142f4'
down_revision = 'd1a600144975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['follower.id'], name='user_project_follower_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_project_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'follower_id', name='user_project_pkey')
    )
    # ### end Alembic commands ###
