"""empty message

Revision ID: bafc6c9f3f14
Revises: b55a9bafc06a
Create Date: 2023-06-06 00:13:58.683593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc6c9f3f14'
down_revision = 'b55a9bafc06a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_follower', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_user_follower_id', table_name='user_follower')
    op.create_index(op.f('ix_user_follower_id'), 'user_follower', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_follower_id'), table_name='user_follower')
    op.create_index('ix_user_follower_id', 'user_follower', ['id'], unique=False)
    op.alter_column('user_follower', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
