"""empty message

Revision ID: 80c5a56db69d
Revises: bafc6c9f3f14
Create Date: 2023-06-06 00:16:46.217089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c5a56db69d'
down_revision = 'bafc6c9f3f14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_follower_id', table_name='user_follower')
    op.drop_column('user_follower', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_follower', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_user_follower_id', 'user_follower', ['id'], unique=False)
    # ### end Alembic commands ###
