"""empty message

Revision ID: 9e9f85491929
Revises: 1d4cba5142f4
Create Date: 2023-06-05 21:07:26.208451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9f85491929'
down_revision = '1d4cba5142f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_follower', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_follower_id'), 'user_follower', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_follower_id'), table_name='user_follower')
    op.drop_column('user_follower', 'id')
    # ### end Alembic commands ###
