"""empty message

Revision ID: b24c52ad1750
Revises: 0f6ae45db477
Create Date: 2023-06-07 01:47:44.127299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24c52ad1750'
down_revision = '0f6ae45db477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('private_key', sa.String(), nullable=False))
    op.add_column('user', sa.Column('public_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_private_key'), 'user', ['private_key'], unique=True)
    op.create_index(op.f('ix_user_public_key'), 'user', ['public_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_public_key'), table_name='user')
    op.drop_index(op.f('ix_user_private_key'), table_name='user')
    op.drop_column('user', 'public_key')
    op.drop_column('user', 'private_key')
    # ### end Alembic commands ###
